#!/usr/bin/env bash
#Install nginx web server and Redirection
sudo apt-get install -y nginx
sudo service nginx start
echo "Holberton School." | sudo tee /usr/share/nginx/html/index.html
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
new_string="location /redirect_me {\nrewrite ^/redirect_me(.*) https://www.google.com permanent;\n}"
sudo sed -i "29i $new_string" /etc/nginx/sites-available/default
sudo service nginx start
