#!/usr/bin/env bash
# Sets up a brand new nginx server with a custom 404 page
sudo apt-get update
sudo apt-get install -y nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i '26s/^/        rewrite ^\/redirect_me\/ https:\/\/www.google.com permanent\;\n/' /etc/nginx/sites-available/default
echo -e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i 's|#error_page 404 \/404.html|error_page 404 \/404.html|' /etc/nginx/sites-available/default
sudo service nginx start
