#!/usr/bin/env bash
#Run Nginx as Nginx
pkill -9 apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed  -i -e 's/listen 80 default_server/listen 8080 default_server/' -e 's/listen [::]:80 default_server/listen [::]:8080 default_server/' /etc/nginx/sites-enabled/default
sed  -i -e 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo -u nginx service nginx start
