#!/usr/bin/env bash
#Run Nginx as Nginx
pkill -9 apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/\(\s*listen[][ \t:]*\)80 /\18080 /' /etc/nginx/sites-enabled/default
sed  -i -e 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo -u nginx service nginx start
