#!/usr/bin/env bash
# Sets up a brand new nginx server with a custom 404 page
# shellcheck disable=SC2154
sudo apt-get update
sudo apt-get install -y nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo mkdir /usr/share/nginx/html/images
sudo wget https://raw.githubusercontent.com/SravanthiSinha/holbertonschool-sysadmin_devops/master/0x09-web_server/tvwithmsg.gif -P /usr/share/nginx/html/images
sudo wget https://raw.githubusercontent.com/SravanthiSinha/holbertonschool-sysadmin_devops/master/0x09-web_server/404.html -P /usr/share/nginx/html
sudo sed -i '26s/^/        rewrite ^\/redirect_me\/ https:\/\/www.google.com permanent\;\n/' /etc/nginx/sites-available/default
sudo sed -i 's|#error_page 404 \/404.html|error_page 404 \/404.html|' /etc/nginx/sites-available/default
sudo sed -i '74s/^/        add_header X-Served-By '"$hostname"'\;\n/' /etc/nginx/nginx.conf
sudo service nginx start
