#!/usr/bin/env bash
# Sets up a brand new nginx server with a custom header response
config="\
server {
	listen 80;
	location / {
		root /usr/share/nginx/html;
		index index.html;
		add_header X-Served-By \$hostname;
	}

	location /redirect_me {
		return 301 https://www.google.com;
	}

	error_page 404 /404-custom.html;

	location /404-custom.html {
		root /usr/share/nginx/html;
		internal;
	}
}
"
sudo apt-get install -y nginx > /dev/null 2>&1
service nginx stop > /dev/null 2>&1
rm -rf /etc/nginx/sites-enabled/* /usr/share/nginx/html/* > /dev/null 2>&1
echo "$config" > /etc/nginx/sites-enabled/holberton
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo mkdir /usr/share/nginx/html/images
sudo wget https://raw.githubusercontent.com/SravanthiSinha/holbertonschool-sysadmin_devops/master/0x09-web_server/tvwithmsg.gif -P /usr/share/nginx/html/images
sudo wget https://raw.githubusercontent.com/SravanthiSinha/holbertonschool-sysadmin_devops/master/0x09-web_server/404.html -O /usr/share/nginx/html/404-custom.html
service nginx start
