#!/usr/bin/env bash
#Install and configure HAproxy on a server.
config="
global
        log 127.0.0.1 local0 notice
        maxconn 2000
        user haproxy
        group haproxy

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        retries 3
        option redispatch
        timeout connect  5000
        timeout client  10000
        timeout server  10000

listen appname 0.0.0.0:80
        mode http
        stats enable
        stats uri /haproxy?stats
        stats realm Strictly\ Private
        stats auth A_Username:YourPassword
        stats auth Another_User:passwd
        balance roundrobin
        option httpclose
        option forwardfor
        server 37-web-01 158.69.91.91:80 check
        server 37-web-02 54.89.82.140:80 check
"
sudo apt-get install -y haproxy
sudo sed -i 's|ENABLED=0|ENABLED=1|' /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
echo "$config" > /etc/haproxy/haproxy.cfg
sudo service haproxy start
