#!/usr/bin/env bash
#Bash (init) script that manages manage_my_process
if [ "$1" = "start" ]; then
    ./manage_my_process &
    sudo sh -c "echo '$(pgrep -f ./manage_my_process)' > /var/run/my_process.pid"
    echo 'manage_my_process started'
elif [ "$1" = "stop" ]; then
    sudo pkill -f ./manage_my_process
    sudo rm -f /var/run/my_process.pid
    echo 'manage_my_process stopped'
elif [ "$1" = "restart" ]; then
    sudo pkill -f ./manage_my_process
    sudo rm -f /var/run/my_process.pid
    ./manage_my_process &
    sudo sh -c "echo '$(pgrep -f ./manage_my_process)' > /var/run/my_process.pid"
    echo 'manage_my_process restarted'
else
    echo 'Usage: manage_my_process {start|stop|restart}'
fi
