#!/usr/bin/env bash
#A Bash script that displays To infinity and beyond indefinitely. and I am invincible!!! when receiving a SIGTERM signal
while true; do
    echo "To infinity and beyond"
    sleep 2
    trap "echo I am invincible!!!" SIGTERM
done
    
